"""Transport-neutral message delivery abstraction.

Proactive messages are generated by the shared chat engine and then delivered
via the appropriate transport adapter.  The scheduler never talks to Telegram
or any other transport directly.

Web transport
-------------
Web sessions do not currently support server-initiated push.  The generated
assistant message is persisted normally so it appears on the next page
refresh or reconnect.  This limitation is documented in
``docs/07-character-card-schedules.md``.
"""
from __future__ import annotations

import logging
from abc import ABC, abstractmethod
from pathlib import Path

logger = logging.getLogger(__name__)


class DeliveryAdapter(ABC):
    """Abstract base for transport-specific message delivery."""

    @abstractmethod
    async def deliver(
        self,
        *,
        channel_instance_id: str,
        external_chat_id: str,
        message_text: str,
    ) -> None:
        """Send *message_text* to the external user.

        Implementations must be idempotent with respect to the message content
        (i.e. do not generate a new LLM reply here — use the pre-generated text).

        Args:
            channel_instance_id: e.g. Telegram bot ID.
            external_chat_id:    e.g. Telegram chat ID.
            message_text:        The assistant response text to deliver.
        """


class WebDeliveryAdapter(DeliveryAdapter):
    """No-op delivery for web sessions.

    The chat engine already persisted the message to the conversation history.
    Web clients pick it up on the next refresh or SSE reconnect.
    """

    async def deliver(
        self,
        *,
        channel_instance_id: str,
        external_chat_id: str,
        message_text: str,
    ) -> None:
        logger.debug(
            "WebDeliveryAdapter: message persisted for external_chat_id=%s "
            "(will appear on next web refresh)",
            external_chat_id,
        )


class TelegramDeliveryAdapter(DeliveryAdapter):
    """Deliver a pre-generated message to a Telegram chat.

    Requires aiogram to be installed (it is an optional dependency for the
    Telegram integration).  If it is not available the delivery is skipped and
    a warning is logged.
    """

    def __init__(self, data_dir: Path | str) -> None:
        self._data_dir = Path(data_dir)

    async def deliver(
        self,
        *,
        channel_instance_id: str,
        external_chat_id: str,
        message_text: str,
    ) -> None:
        try:
            from aiogram import Bot
        except ImportError:
            logger.warning("TelegramDeliveryAdapter: aiogram is not installed; skipping delivery")
            return

        from ..services.telegram_bot_service import TelegramBotService

        svc = TelegramBotService(self._data_dir)
        try:
            token = svc.get_bot_token(channel_instance_id)
        except KeyError:
            logger.warning(
                "TelegramDeliveryAdapter: bot %s not found; skipping delivery",
                channel_instance_id,
            )
            return

        bot = Bot(token=token)
        try:
            chat_id_int = int(external_chat_id)
        except ValueError:
            logger.error(
                "TelegramDeliveryAdapter: invalid chat_id %r; skipping delivery",
                external_chat_id,
            )
            return

        # Split long messages the same way the runtime manager does.
        from ..services.telegram_runtime_manager import split_message

        try:
            for chunk in split_message(message_text):
                await bot.send_message(chat_id=chat_id_int, text=chunk)
        except Exception:
            logger.exception(
                "TelegramDeliveryAdapter: failed to send to chat_id=%s via bot=%s",
                external_chat_id,
                channel_instance_id,
            )
        finally:
            await bot.session.close()


def make_delivery_adapter(channel: str, data_dir: Path | str) -> DeliveryAdapter:
    """Factory — return the right adapter for *channel*."""
    if channel == "telegram":
        return TelegramDeliveryAdapter(data_dir)
    # "web" or any unknown channel → persist-only
    return WebDeliveryAdapter()
