"""Transport-neutral message delivery abstraction.

Proactive messages are generated by the shared chat engine and then delivered
via the appropriate transport adapter.  The scheduler never talks to Telegram
or any other transport directly.

Web transport
-------------
Web sessions are pushed through the in-process event bus, which already backs
the ``GET /api/chat/{id}/events`` SSE endpoint used for multi-tab delivery.
The adapter publishes a ``typing`` status while the message is generated and
then the message itself as ``token`` + ``done`` events, so an open tab renders
it live.  The message is also persisted by the scheduler, so tabs that were
closed still see it on the next refresh.
"""
from __future__ import annotations

import contextlib
import logging
from abc import ABC, abstractmethod
from collections.abc import AsyncIterator
from pathlib import Path

from ..event_bus import get_event_bus
from .observability_service import get_registry, record_error

logger = logging.getLogger(__name__)


class DeliveryAdapter(ABC):
    """Abstract base for transport-specific message delivery."""

    @abstractmethod
    async def deliver(
        self,
        *,
        channel_instance_id: str,
        external_chat_id: str,
        message_text: str,
        conversation_id: str = "",
    ) -> None:
        """Send *message_text* to the external user.

        Implementations must be idempotent with respect to the message content
        (i.e. do not generate a new LLM reply here — use the pre-generated text).

        Args:
            channel_instance_id: e.g. Telegram bot ID.
            external_chat_id:    e.g. Telegram chat ID, or the web session token.
            message_text:        The assistant response text to deliver.
            conversation_id:     Conversation the message belongs to (web push).
        """

    @contextlib.asynccontextmanager
    async def typing(
        self,
        *,
        channel_instance_id: str,
        external_chat_id: str,
        conversation_id: str = "",
    ) -> AsyncIterator[None]:
        """Show a "composing" status on the transport for the duration of the block.

        Default implementation is a no-op.  Never raises: the status is
        cosmetic and must never break the generation it wraps.
        """
        yield


class WebDeliveryAdapter(DeliveryAdapter):
    """Push a proactive message to open web tabs via the event bus.

    The bus is keyed by ``(session_token, conversation_id)``; for the web
    channel ``external_chat_id`` *is* the session token (see
    ``routers/chat.get_chat_service``).  Tabs with no open SSE connection lose
    nothing: the scheduler persisted the message before calling us.
    """

    @contextlib.asynccontextmanager
    async def typing(
        self,
        *,
        channel_instance_id: str,
        external_chat_id: str,
        conversation_id: str = "",
    ) -> AsyncIterator[None]:
        """Publish a typing status for the duration of the block."""
        if not external_chat_id or not conversation_id:
            yield
            return

        bus = get_event_bus()
        with contextlib.suppress(Exception):
            await bus.publish(
                external_chat_id, conversation_id, {"type": "typing", "state": "start"}
            )
        try:
            yield
        finally:
            with contextlib.suppress(Exception):
                await bus.publish(
                    external_chat_id, conversation_id, {"type": "typing", "state": "stop"}
                )

    async def deliver(
        self,
        *,
        channel_instance_id: str,
        external_chat_id: str,
        message_text: str,
        conversation_id: str = "",
    ) -> None:
        if not external_chat_id or not conversation_id:
            logger.debug(
                "WebDeliveryAdapter: no session token or conversation id; "
                "message persisted only (will appear on next web refresh)",
            )
            return

        # Same event shape as a normal streamed reply, so open tabs render it
        # with the existing remote-SSE handler.
        bus = get_event_bus()
        await bus.publish(
            external_chat_id, conversation_id, {"type": "token", "content": message_text}
        )
        await bus.publish(external_chat_id, conversation_id, {"type": "done"})


class TelegramDeliveryAdapter(DeliveryAdapter):
    """Deliver a pre-generated message to a Telegram chat.

    Requires aiogram to be installed (it is an optional dependency for the
    Telegram integration).  If it is not available the delivery is skipped and
    a warning is logged.
    """

    def __init__(self, data_dir: Path | str) -> None:
        self._data_dir = Path(data_dir)

    @contextlib.asynccontextmanager
    async def typing(
        self,
        *,
        channel_instance_id: str,
        external_chat_id: str,
        conversation_id: str = "",
    ) -> AsyncIterator[None]:
        """Show the Telegram "typing" status while the block runs."""
        from ..services.telegram_runtime_manager import chat_action

        try:
            from aiogram import Bot

            from ..services.telegram_bot_service import TelegramBotService

            token = TelegramBotService(self._data_dir).get_bot_token(channel_instance_id)
            int(external_chat_id)  # reject non-numeric chat ids early
        except Exception:
            # No bot, no aiogram or an unusable chat id — deliver() reports it.
            yield
            return

        bot = Bot(token=token)
        try:
            async with chat_action(bot, external_chat_id):
                yield
        finally:
            with contextlib.suppress(Exception):
                await bot.session.close()

    async def deliver(
        self,
        *,
        channel_instance_id: str,
        external_chat_id: str,
        message_text: str,
        conversation_id: str = "",
    ) -> None:
        try:
            from aiogram import Bot
        except ImportError:
            logger.warning("TelegramDeliveryAdapter: aiogram is not installed; skipping delivery")
            return

        from ..services.telegram_bot_service import TelegramBotService

        svc = TelegramBotService(self._data_dir)
        try:
            token = svc.get_bot_token(channel_instance_id)
        except KeyError:
            logger.warning(
                "TelegramDeliveryAdapter: bot %s not found; skipping delivery",
                channel_instance_id,
            )
            record_error(
                "telegram_delivery",
                "bot not found; proactive delivery skipped",
                bot_id=channel_instance_id,
            )
            return

        bot = Bot(token=token)
        try:
            chat_id_int = int(external_chat_id)
        except ValueError:
            logger.error(
                "TelegramDeliveryAdapter: invalid chat_id %r; skipping delivery",
                external_chat_id,
            )
            record_error(
                "telegram_delivery",
                "invalid chat id; proactive delivery skipped",
                bot_id=channel_instance_id,
            )
            return

        # Split long messages the same way the runtime manager does.
        from ..services.telegram_runtime_manager import split_message

        try:
            for chunk in split_message(message_text):
                await bot.send_message(chat_id=chat_id_int, text=chunk)
        except Exception:
            # Re-raised so the caller can record the execution as failed —
            # swallowing it here made every failed delivery look like a
            # successful send.
            logger.exception(
                "TelegramDeliveryAdapter: failed to send to chat_id=%s via bot=%s",
                external_chat_id,
                channel_instance_id,
            )
            get_registry().mark_delivery_failure(channel_instance_id)
            raise
        else:
            get_registry().mark_message_sent(channel_instance_id)
        finally:
            await bot.session.close()


def make_delivery_adapter(channel: str, data_dir: Path | str) -> DeliveryAdapter:
    """Factory — return the right adapter for *channel*."""
    if channel == "telegram":
        return TelegramDeliveryAdapter(data_dir)
    # "web" or any unknown channel → persist-only
    return WebDeliveryAdapter()
